### ISSUE TITLE
No module match refile==8.0.0.post1

### ISSUE THREAD

**Issue by Yutong18** [megvii-research/MegFaceAnimate#1]
Hi Thank you for your amazing work. There is no matching refile==8.0.0.post1. I tried to use refile==0.4.1 and met following error: 
from refile import smart_open, smart_load_from
ImportError: cannot import name 'smart_open' from 'refile' (/mnt/nfs/file_server/public/yt/miniconda3/envs/test/lib/python3.10/site-packages/refile/__init__.py)
Could you help me with this problem. Thank you!

**Comment by EvePhil** [comment]
Thanks for the report! 
"refile" is an unnecessary dependency and now has been removed.

**Comment by 907491795** [comment]
I miss the same problem in sigma

File "/animate/megactor-sigma/animate.py", line 28, in
from refile import smart_open, smart_load_from
ImportError: cannot import name 'smart_open' from 'refile' (/home/anaconda3/envs/megactor-sigma/lib/python3.10/site-packages/refile/init.py)

How can I solve it ？
